version: 2
jobs:
  build-go1.11-gomodules:
    filters:
      branches:
        only: ci
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/app
    steps:
      - checkout
      - run: go test -race
      - setup_remote_docker
      - run:
          name: Install awscli
          command: |
            sudo apt-get install python3-pip
            pip install -r requirements.txt
      - run:
          name: Create executable
          command: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o build/app-docker main.go
      - run:
          name: Set convinience environment variables
          command: |
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
            echo 'export ECR_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}"' >> $BASH_ENV
            echo 'export CIRCLE_IMAGE_NAME="${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"' >> $BASH_ENV
            echo 'export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV

      - run:
          name: Build Image
          command: docker build -t ${CIRCLE_IMAGE_NAME} .
      - run:
          name: Test Image
          command: |
            docker run -d -p 8080:8080 --name build-image $CIRCLE_IMAGE_NAME
      - run:
          name: Push image
          command: |
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker tag ${CIRCLE_IMAGE_NAME} ${ECR_IMAGE_NAME}
            docker push ${ECR_IMAGE_NAME}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-go1.11-gomodules
