version: 2
jobs:
  build-go1.11-gomodules:
    filters:
      branches:
        only: ci
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/app
    steps:
      - checkout
      - run: go test -race

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-go1.11-gomodules
